#主配置文件
spring:
  # 激活环境配置
  profiles:
    active: dev

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hit.spectrum.data
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml